$stc('', '../art', 'web', 'web/both',
		
		  'web/events',
		'web/css', 'web/dom', 'web/html', 'web/js',
		
		'web/front/wid',
		'web/front/nok',
		'web/front/bone',
		'web/front/sync',
		'graphics', 'graphics/can', 'graphics/gpc', 'graphics/ctx',
		'easel',
		'easel/bitmap', 'easel/dob', 'easel/dobs', 'easel/draw', 'easel/events',
		'easel/filter', 'easel/shapes',
		'anim',
		'anim/flash',
		'anim/sprite',
		'anim/movieClip',
		'mashUp', 'sync',
		'wappy', 'wappy/work',
		'wappy/muggy',
		'muggy',
		'fiz/box',
		'fiz',
		'box/core',
		'box',
		'box/body', 'box/fixture', 'box/shapes', 'box/world',
		'fiz/bods', 'fiz/fixts', 'fiz/shapes', 'fiz/world',
		'box/geo', 'box/collide',
		'worldQuery', 'collide', 'joints', 'control', 'yip', 'arcade', 'games', 'geo',
		'bxApps',
		'Joints',
		'fiz/body', 'fiz/fixture', 'fiz/world', 'fiz/joint', 'fiz/query', 'fiz/collide', 'fiz/control',
		'fiz/box/body', 'fiz/box/fixture', 'fiz/box/world', 'fiz/box/core'
)